spring:
    application:
        name: privatelog

    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://hopper.proxy.rlwy.net:43536/railway}
        username: ${SPRING_DATASOURCE_USERNAME:postgres}
        password: ${SPRING_DATASOURCE_PASSWORD:XaNvgxLBdRwFLtgZXHvpNWlMEzbmdxNT}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true

server:
    port: ${PORT:8080}

jwt:
    secret: ${JWT_SECRET:privatelog-jwt-secret-key-for-hs256-algorithm-minimum-256bits}
    expiration: ${JWT_EXPIRATION:86400000}
