spring:
    application:
        name: privatelog

    datasource:
        #url: jdbc:postgresql://localhost:5432/privatelog
        url: jdbc:postgresql://hopper.proxy.rlwy.net:43536/railway
        username: postgres
        password: XaNvgxLBdRwFLtgZXHvpNWlMEzbmdxNT
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        show-sql: true

jwt:
    secret: privatelog-jwt-secret-key-for-hs256-algorithm-minimum-256bits
    expiration: 86400000
